version: '3'
services:
  security_the_toolbox:
    build: ./security_the_toolbox
    container_name: security_the_toolbox
    volumes:
      - ./security_the_toolbox:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - security_network

networks:
  security_network:
    driver: bridge